config/routes.rb
Rails.application.routes.draw do
  root 'rides#index'	
  resources :drivers
  resources :customers
  resources :rides
  patch 'select_ride', :to => 'drivers#select_ride'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :rides
end

app/models/driver.rb
class Driver < ApplicationRecord
end

app/models/ride.rb
class Ride < ApplicationRecord
  belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name)
    end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy]

  # GET /drivers
  # GET /drivers.json
  def index
    @drivers = Driver.all
    @rides = Ride.all
  end

  # GET /drivers/1
  # GET /drivers/1.json
  def show
    @rides = Ride.all
  end

  # GET /drivers/new
  def new
    @driver = Driver.new
  end

  # GET /drivers/1/edit
  def edit
  end

  # POST /drivers
  # POST /drivers.json
  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: 'Driver was successfully created.' }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1
  # PATCH/PUT /drivers/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  def select_ride
    driver_id = params[:driver_id]
    Ride.find(params[:ride_id]).update_attributes(:driver_id => driver_id, status: "ongoing", pickup_time: Time.now)
    UpdateRideStatusWorker.perform_in(5.minutes,params[:ride_id])
    @rides = Ride.all
    @driver = Driver.find(driver_id)
    redirect_to @driver, notice: "Ride successfully selected."
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.json
  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url, notice: 'Driver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def driver_params
      params.require(:driver).permit(:name)
    end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  before_action :set_ride, only: [:show, :edit, :update, :destroy]

  # GET /rides
  # GET /rides.json
  def index
    @rides = Ride.all
  end

  # GET /rides/1
  # GET /rides/1.json
  def show
  end

  # GET /rides/new
  def new
    @ride = Ride.new
  end

  # GET /rides/1/edit
  def edit
  end

  # POST /rides
  # POST /rides.json
  def create
    @ride = Ride.new(ride_params)
    respond_to do |format|
      if @ride.save
        format.html { redirect_to @ride, notice: 'Ride was successfully created.' }
        format.json { render :show, status: :created, location: @ride }
      else
        format.html { render :new }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rides/1
  # PATCH/PUT /rides/1.json
  def update
    respond_to do |format|
      if @ride.update(ride_params)
        format.html { redirect_to @ride, notice: 'Ride was successfully updated.' }
        format.json { render :show, status: :ok, location: @ride }
      else
        format.html { render :edit }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rides/1
  # DELETE /rides/1.json
  def destroy
    @ride.destroy
    respond_to do |format|
      format.html { redirect_to rides_url, notice: 'Ride was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ride
      @ride = Ride.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ride_params
      params.require(:ride).permit(:customer_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :customer_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/drivers/_form.html.erb
<%= form_with(model: driver, local: true) do |form| %>
  <% if driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
      <% driver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :driver_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/drivers/edit.html.erb
<h1>Editing Driver</h1>

<%= render 'form', driver: @driver %>


<%= link_to 'Back', drivers_path %>

app/views/drivers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Drivers</h1>

<table>
  <thead>
    <tr>
      <th>DriverId</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drivers.each do |driver| %>
      <tr>
        <td><%= driver.id %></td>
        <td><%= driver.name %></td>
        <td><%= link_to 'Select Driver', driver %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Driver', new_driver_path %>

app/views/drivers/new.html.erb
<h1>New Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Back', drivers_path %>

app/views/drivers/show.html.erb
<style>
	body {
   background: #999;  
   padding: 20px 40px; 
}

.tabs {
  position: relative;   
  min-height: 600px;
  clear: both;
  margin: 35px 0 25px;
  background: white;
}
.tab {
  float: left;
   
}
.tab label {
  background: #eee; 
  padding: 10px; 
  border: 1px solid #ccc; 
  margin-left: -1px; 
  position: relative;
  left: 1px; 
  top: -29px;
  -webkit-transition: background-color .17s linear;
}
.tab [type=radio] {
  display: none;   
}
.content {
  position: absolute;
  top: -1px;
  left: 0;
  background: white;
  right: 0;
  bottom: 0;
  padding: 20px;
  border: 1px solid #ccc; 
  -webkit-transition: opacity .6s linear;
  opacity: 0;
}
[type=radio]:checked ~ label {
  background: white;
  border-bottom: 1px solid white;
  z-index: 2;
}
[type=radio]:checked ~ label ~ .content {
  z-index: 1;
  opacity: 1;
}

table, td, th {    
    border: 1px solid #ddd;
    text-align: left;
}

table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    padding: 15px;
}
</style>
<p id="notice"><%= notice %></p>
<%= button_to "Refresh", driver_path, :method => :get %>


<div class="tabs">

    
   <div class="tab">
       <input type="radio" id="tab-1" name="tab-group-1" checked>
       <label for="tab-1">Waiting</label>
       
       <div class="content">
           <table>
  <thead>
    <tr>
      <th>RequestID</th>
      <th>CustomerID</th>
      <th>Requested</th>
    </tr>
  </thead>

  <tbody>
    <% @rides.each do |ride| %>
    <% if ride.status == "waiting" %>
      <tr>
        <td><%= ride.id %></td>
        <td><%= ride.customer.id%></td>
        <td><%= time_ago_in_words((ride.created_at).localtime) %><%= " ago"%></td>
        <td><%= button_to 'Select Ride', select_ride_path(:ride_id => ride.id, :driver_id => @driver.id), :method => :patch %></td>
        </tr>
        <% end %>
    <% end %>
  </tbody>
</table>
       </div> 
   </div>
    
   <div class="tab">
       <input type="radio" id="tab-2" name="tab-group-1">
       <label for="tab-2">Ongoing</label>
       
       <div class="content">
          <table>
  <thead>
  
    <tr>
      <th>RequestID</th>
      <th>CustomerID</th>
      <th>Requested</th>
      <th>PickedUp</th>
    </tr>
  </thead>

  <tbody>
    <% @rides.each do |ride| %>
<% if ride.status == "ongoing" && ride.driver_id == @driver.id  %>
      <tr>
        <td><%= ride.id %></td>
        <td><%= ride.customer.id%></td>
        <td><%= time_ago_in_words((ride.created_at).localtime) %><%= " ago"%></td>
        <td><%= time_ago_in_words((ride.pickup_time).localtime) %><%= " ago"%></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
           
       </div> 
   </div>
    
    <div class="tab">
       <input type="radio" id="tab-3" name="tab-group-1">
       <label for="tab-3">Complete</label>
     
       <div class="content">
         <table>
  <thead>
    <tr>
      <th>RequestID</th>
      <th>CustomerID</th>
      <th>Requested</th>
      <th>PickedUp</th>
      <th>Completed</th>
    </tr>
  </thead>

  <tbody>
    <% @rides.each do |ride| %>
<% if ride.status == "complete" && ride.driver_id == @driver.id  %>
      <tr>
        <td><%= ride.id %></td>
        <td><%= ride.customer.id%></td>
        <td><%= time_ago_in_words((ride.created_at).localtime) %><%= " ago"%></td>
        <td><%= time_ago_in_words((ride.pickup_time).localtime) %><%= " ago"%></td>
        <td><%= time_ago_in_words((ride.updated_at).localtime) %><%= " ago"%></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
           
       </div> 
   </div>
    
</div>




<p>
  <strong>Name:</strong>
  <%= @driver.id %>
</p>



 
<%= link_to 'Back', drivers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OlaQueuingSystem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rides/_form.html.erb
<%= form_with(model: ride, local: true) do |form| %>
  <% if ride.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ride.errors.count, "error") %> prohibited this ride from being saved:</h2>

      <ul>
      <% ride.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.select :customer_id, Customer.all.collect { |c| [ c.name, c.id ] }, include_blank: true, id: :ride_customer_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rides/edit.html.erb
<h1>Editing Ride</h1>

<%= render 'form', ride: @ride %>

<%= link_to 'Show', @ride %> |
<%= link_to 'Back', rides_path %>

app/views/rides/index.html.erb
<style>
table, td, th {    
    border: 1px solid #ddd;
    text-align: left;
}

table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    padding: 15px;
}
</style>
<p id="notice"><%= notice %></p>

<%= button_to "Refresh", rides_path, :method => :get %>

<h1>Dashboard</h1>

<%= button_to 'Create Drive Account', new_driver_path, :method => :get %>
<%= button_to 'Create Customer Account', new_customer_path, :method => :get %>
<table>
  <thead>
    <tr>
      <th>RequestID</th>
      <th>CustomerID</th>
      <th>Time Elapsed</th>
      <th>Status</th>
      <th>Driver</th>
    </tr>
  </thead>

  <tbody>
    <% @rides.each do |ride| %>
      <tr>
        <td><%= ride.id %></td>
        <td><%= ride.customer.id %></td>
        <td><%= time_ago_in_words((ride.created_at).localtime) %><%= " ago"%></td>
        <td><%= ride.status %></td>
        <% if ride.driver_id %>
        <td><%= ride.driver_id %></td>
        <% else %>
        <td><%= "none" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/rides/new.html.erb
<h1>New Ride</h1>

<%= render 'form', ride: @ride %>

<%= link_to 'Back', rides_path %>

app/views/rides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @ride.status %>
</p>

<% if @ride.pickup_time %>
<p>
  <strong>Pickup time:</strong>
   
  <%= @ride.pickup_time %>
</p>
<% else %>
  <p>
  <strong>Request Time:</strong>
   
  <%= @ride.created_at %>
</p>
  <% end %>

<p>
  <strong>Driver:</strong>
  <% if @ride.driver_id %>
  <%= @ride.driver_id %>
  <% else %>
  <%= "none" %>
  <% end %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @ride.customer.name %>
</p>


<%= link_to 'Back', rides_path %>